


// Contact c = new Contact(email='a@gmail.com', FirstName='f4', LastName = 'l', Mesto_soukrome__c = null);
// Contact c2 = new Contact(email='a@gmail.com', FirstName='f2', LastName = 'l');

// Database.upsert(new List<Contact>{c}, Contact.Email);

// Logger.init('001xa000003DIlo');
// DarujmeLoader.loadTransactions('2022-03-21', null);
// Logger.closeAndStore();

System.debug(new AdapterraFetcher().getNominations());